### PR TITLE
Update for the changes in cisagov/openvpn-server-tf-module#91

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull request:
- Updates this Terraform code for the changes made in cisagov/openvpn-server-tf-module#91.
- Removes some leftover cruft related to the installation of Tanium and Tenable agents.  We no longer install that software in [cisagov/openvpn-packer](https://github.com/cisagov/openvpn-packer).

## 💭 Motivation and context ##

- As is explained in cisagov/openvpn-server-tf-module#91, the CrowdStrike Falcon sensor must be deployed to our OpenVPN instances in order to maintain our ATO.
- Removed code is code that cannot contain bugs.

## 🧪 Testing ##

All automated tests pass.  In addition, I used these changes to deploy a new OpenVPN instance to our staging COOL environment and verified that:
- OpenVPN still functions.
- The CrowdStrike Falcon sensor has the correct customer ID and tags and starts up successfully.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated to reflect the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [x] Revert to the default branch of [cisagov/openvpn-server-tf-module](https://github.com/cisagov/openvpn-server-tf-module) once cisagov/openvpn-server-tf-module#91 is merged.

### CODE REVIEW

**Review by jasonodoom — APPROVED** [review]

**Review by dav3r — APPROVED** [review]
As with the other related PRs, please mention that this PR also includes the removal of Nessus-related bits.

**Comment by jsf9k** [comment]
> As with the other related PRs, please mention that this PR also includes the removal of Nessus-related bits.

PR description updated.

**Review by dav3r — APPROVED** [review]
image

**Review by mcdonnnj — APPROVED** [review]
:shipit:

**Review by jasonodoom — APPROVED** [review]

**Pull request merged**
